---
- name: Learn about localhost
  hosts: localhost
  tags:
    - always
  tasks:
    - ansible.builtin.debug:
        msg: Running on {{ ansible_facts['distribution'] }}
        verbosity: 0

    - name: Classify hosts depending on their OS distribution
      ansible.builtin.group_by:
        key: distro_{{ ansible_facts['distribution'] }}

- import_playbook: packages.yml
- import_playbook: system.yml
- import_playbook: docker.yml
- import_playbook: user.yml
- import_playbook: sway.yml
- import_playbook: homebrew.yml
