---
- name: Install Docker and Compose (Fedora)
  hosts: distro_Fedora
  become: true
  tags:
    - dev
    - docker
  tasks:
    - name: Set CGroups to V1
      ansible.builtin.command:
        argv:
          - grubby
          - --update-kernel=ALL
          - --args="systemd.unified_cgroup_hierarchy=0"

    - name: Add docker0 interface to trusted zone
      ansible.builtin.command:
        argv:
          - firewall-cmd
          - --permanent
          - --zone=trusted
          - --add-interface=docker0

    - name: Add masquerading to FedoraWorkstation zone
      ansible.builtin.command:
        argv:
          - firewall-cmd
          - --permanent
          - --zone=FedoraWorkstation
          - --add-masquerade

    - name: Install
      ansible.builtin.dnf:
        name:
          - moby-engine
          - docker-compose
        state: latest

    - name: Enable docker service
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        masked: no

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_env.USER }}"
        groups: docker
        append: yes
      ignore_errors: yes

- name: Install Docker (Ubuntu)
  hosts:
    - distro_Ubuntu
    - distro_Pop!_OS
  become: true
  tags:
    - dev
    - docker
  tasks:
    - name: Add GPG key
      ansible.builtin.apt_key:
        keyserver: https://download.docker.com/linux/ubuntu/gpg
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        state: present

    - name: Add repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        filename: docker
        state: present
        validate_certs: yes

    - name: Install
      ansible.builtin.apt:
        name:
          - containerd.io
          - docker-ce
          - docker-ce-cli
        update_cache: yes
        state: latest

    - name: Enable docker service
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        masked: no

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_env.USER }}"
        groups: docker
        append: yes
      ignore_errors: yes

- name: Install Docker Compose (Ubuntu)
  hosts:
    - distro_Ubuntu
    - distro_Pop!_OS
  vars:
    compose_version: 1.27.4
  tags:
    - dev
    - docker
    - docker-compose
  tasks:
    - ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-Linux-x86_64
        dest: "{{ ansible_env.HOME }}/.local/bin/docker-compose"
        mode: "0755"

    - name: Create Bash completion directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/share/bash-completion/completions/"
        state: directory
        mode: "0755"

    - name: Download Bash completion script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/docker/compose/{{ compose_version }}/contrib/completion/bash/docker-compose
        dest: "{{ ansible_env.HOME }}/.local/share/bash-completion/completions/docker-compose"
