---
- name: Change shell
  hosts: localhost
  vars_files:
    - vars/user.yml
  tags:
    - fish
    - shell
    - user
    - zsh
  tasks:
    - name: Get path to chosen shell
      ansible.builtin.command:
        argv:
          - which
          - "{{ login_shell }}"
      register: shell_path

    - name: Change shell
      become: true
      ansible.builtin.user:
        name: "{{ ansible_env.USERNAME }}"
        shell: "{{ shell_path.stdout }}"

- name: Link config files
  hosts: localhost
  tags:
    - user
    - shell
    - sway
  tasks:
    - name: Link files to $HOME
      ansible.builtin.file:
        src: "{{ playbook_dir }}/../home/{{ item }}"
        dest: "{{ ansible_env.HOME }}/{{ item }}"
        state: link
      loop:
        - .bash_profile
        - .bashrc
    - name: Link files to $HOME/.config/
      ansible.builtin.file:
        src: "{{ playbook_dir }}/../home/.config/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.config/{{ item }}"
        state: link
      loop:
        - alacritty
        - fish
        - gammastep
        - mako
        - sway
        - waybar

- name: Create SSH key
  hosts: localhost
  vars_files:
    - vars/user.yml
  tags:
    - dev
    - git
    - ssh
    - user
  tasks:
    - ansible.builtin.user:
        name: "{{ ansible_env.USERNAME }}"
        generate_ssh_key: yes
        ssh_key_type: "{{ ssh_key_type }}"
        ssh_key_file: "{{ ssh_key_file }}"
        ssh_key_comment: "{{ user_email | default(omit) }}"

    - name: Start SSH agent
      shell: eval "$(ssh-agent -s)"

    - name: Add key to SSH agent
      ansible.builtin.command:
        argv:
          - ssh-add
          - "{{ ssh_key_file }}"

- name: Configure git
  hosts: localhost
  vars_files:
    - vars/user.yml
  tags:
    - dev
    - git
    - user
  tasks:
    - block:
      - name: Check required variables exist and have values
        ansible.builtin.assert:
          that:
            - "{{ item }} is defined"
            - "{{ item }} != None"
            - "{{ item }} | length > 0"
          fail_msg: "Variable {{ item }} is required. Please set it on vars/user.yml"
          success_msg: "Required variable {{ item }} is defined"
        loop:
          - user_name
          - user_email

      - name: Set global user.name
        ansible.builtin.command:
          argv:
            - git
            - config
            - --global
            - user.name
            - "{{ user_name }}"

      - name: Set global user.email
        ansible.builtin.command:
          argv:
            - git
            - config
            - --global
            - user.email
            - "{{ user_email }}"
      rescue:
        - ansible.builtin.debug:
            msg: |
              Ignored git config because of undefined variables.
              Check the messages above.
            verbosity: 0
